### ISSUE TITLE
Select a message and message actions toolbar

### ISSUE THREAD

**Issue by mattyg** [holochain-apps/volla-messages#133]
- Long press a message to select it (indicate in UI that it is selected)
- When a message is selected, display actions toolbar
- Potential Actions toolbar actions
   - Copy (copies full content of message)
   - Reply (not implemented yet in DNA)
   - Forward (not implemented yet in DNA)|
   - Hide message
   - Block User
   - Delete (if I authored the message)

**Comment by MasterK0927** [comment]
completed in #292
