### ISSUE TITLE
Some message text styled as red

### ISSUE THREAD

**Issue by mattyg** [holochain-apps/volla-messages#189]
All message text should be the same color. 

![image](https://github.com/user-attachments/assets/5680e7cc-fe0b-4e23-938d-f48ab6cfb8ad)

**Comment by MasterK0927** [comment]
Unable to reproduce the issue on my end. Please confirm if the issue persists and provide details about the platform and any additional steps to reproduce it.

**Comment by mattyg** [comment]
I reproduced the issue in both light & dark mode on both android and ubuntu 22.04, on both develop-0.3 and develop.

It seems to occur with any text where there is a number, followed by a period, followed by another number. See the screenshot for example text.

**Comment by mattyg** [comment]
It looks like they are being rendered as links. 

This should be resolved as part of changes in #279 so we can just address it there.
